### ISSUE TITLE
Max value for accessibility

### ISSUE THREAD

**Issue by pcav** [Geolicious/OSMroute#10]
It is currently 30 min, which seems too low

**Comment by magerlin** [comment]
I Agree!

**Comment by riccardoklinger** [comment]
The openrouteservice.org API only allows values <= 30 min!

reference: http://wiki.openstreetmap.org/wiki/OpenRouteService#OpenRouteService_API

**Comment by magerlin** [comment]
OK - that's sad.... but I can see it has to do with performance
