### ISSUE TITLE
After restart Layers aren't visible

### ISSUE THREAD

**Issue by Theki89** [Geolicious/OSMroute#16]
Hey,

I created with QGIS three accessibility analysis. They ara visible and everything is all right.

After restart a of QGIS and open the project file the three layers aren't visible for me. In the toolbox the stamps are visibile, but on the map I cann't locate them.

**Comment by Schapper** [comment]
Hi,

I get the same issue with memory layers I create. If you want to keep any layers in QGIS, save them as shapefiles after you’ve created them, and delete the former layer.

**Comment by riccardoklinger** [comment]
This is not an issue but more ore less a feature. The layer is created as a memory layer and needs to be safed as a shapefile if you would like to use it later on...
will close this issue

**Comment by riccardoklinger** [comment]
It is stated explicitly here in the readme.md:
"All files need to be saved seperately when needed for further analysis."
