### ISSUE TITLE
class factory issue QGIS 2.8.2 Python. 2.7.2

### ISSUE THREAD

**Issue by ghost** [Geolicious/OSMroute#2]
Konnte Erweiterung OSMroute nicht laden aufgrund eines Fehlers beim Aufruf der classFactory() Methode

Traceback (most recent call last):
  File "C:/PROGRA~2/QGISWI~1/apps/qgis/./python\qgis\utils.py", line 219, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/PROGRA~2/QGISWI~1/apps/qgis/./python/plugins\OSMroute__init__.py", line 34, in classFactory
    from .OSMroute import OSMroute
  File "C:/PROGRA~2/QGISWI~1/apps/qgis/./python\qgis\utils.py", line 478, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/PROGRA~2/QGISWI~1/apps/qgis/./python/plugins\OSMroute\OSMroute.py", line 34, in 
    import urllib2, os, requests, qgis.utils, os.path, resources_rc
  File "C:/PROGRA~2/QGISWI~1/apps/qgis/./python\qgis\utils.py", line 478, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ImportError: No module named requests

Python-Version:
2.7.4 (default, Apr  6 2013, 19:54:46) [MSC v.1500 32 bit (Intel)]

QGIS-Version:
2.8.2-Wien Wien, 1b929ef

Python-Pfad: ['C:/Users/.qgis2/python/plugins\processing', 'C:/PROGRA~2/QGISWI~1/apps/qgis/./python', u'C:/Users/.qgis2/python', u'C:/Users/.qgis2/python/plugins', 'C:/PROGRA~2/QGISWI~1/apps/qgis/./python/plugins', 'C:\PROGRA~2\QGISWI~1\bin\python27.zip', 'C:\PROGRA~2\QGISWI~1\apps\Python27\DLLs', 'C:\PROGRA~2\QGISWI~1\apps\Python27\lib', 'C:\PROGRA~2\QGISWI~1\apps\Python27\lib\plat-win', 'C:\PROGRA~2\QGISWI~1\apps\Python27\lib\lib-tk', 'C:\PROGRA~2\QGISWI~1\bin', 'C:\PROGRA~2\QGISWI~1\apps\Python27', 'C:\PROGRA~2\QGISWI~1\apps\Python27\lib\site-packages', 'C:\PROGRA~2\QGISWI~1\apps\Python27\lib\site-packages\PIL', 'C:\PROGRA~2\QGISWI~1\apps\Python27\lib\site-packages\jinja2-2.7.2-py2.7.egg', 'C:\PROGRA~2\QGISWI~1\apps\Python27\lib\site-packages\markupsafe-0.23-py2.7-win32.egg', 'C:\PROGRA~2\QGISWI~1\apps\Python27\lib\site-packages\python_dateutil-2.2-py2.7.egg', 'C:\PROGRA~2\QGISWI~1\apps\Python27\lib\site-packages\pytz-2014.2-py2.7.egg', 'C:\PROGRA~2\QGISWI~1\apps\Python27\lib\site-packages\win32', 'C:\PROGRA~2\QGISWI~1\apps\Python27\lib\site-packages\win32\lib', 'C:\PROGRA~2\QGISWI~1\apps\Python27\lib\site-packages\Pythonwin', 'C:\PROGRA~2\QGISWI~1\apps\Python27\lib\site-packages\Shapely-1.2.18-py2.7-win32.egg', 'C:\PROGRA~2\QGISWI~1\apps\Python27\lib\site-packages\six-1.6.1-py2.7.egg', 'C:\PROGRA~2\QGISWI~1\apps\Python27\lib\site-packages\wx-2.8-msw-unicode', u'C:/Users/.qgis2//python', 'C:\PROGRA~2\QGISWI~1\apps\qgis\python\plugins\fTools\tools']

**Comment by riccardoklinger** [comment]
welches OS? Windows 7 64 bit? normally requests is a standard library...

**Comment by riccardoklinger** [comment]
deleted the import of module requests as it is not needed in the current code

**Comment by ghost** [comment]
tested on windows 7 64bit and 32bit + QGIS 2.2.0/2.8.2 python 2.7.2

**Comment by riccardoklinger** [comment]
okay. new version is in the repo and the qgis plugin path without calling 
    import requests
...

**Comment by riccardoklinger** [comment]
should install now, please test @enricosteiger

**Comment by ghost** [comment]
already tested works great I'll commit some minor UI handling/usability issues later

**Comment by riccardoklinger** [comment]
great! thanks for testing!
